spring:
  application:
    name: configcat-demo
  profiles:
    active: local
    
server:
  port: 8080

# Logging configuration
logging:
  level:
    com.example.configcat: INFO
    com.configcat: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId:-}] [%X{userId:-}] %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,configcat
  endpoint:
    health:
      show-details: always
    configcat:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# ConfigCat configuration
configcat:
  log-level: INFO
  user-management:
    sdk-key: "YOUR_USER_MANAGEMENT_SDK_KEY"
    poll-interval-seconds: 30
  payment:
    sdk-key: "YOUR_PAYMENT_SDK_KEY"
    poll-interval-seconds: 30

---
spring:
  config:
    activate:
      on-profile: local

configcat:
  log-level: DEBUG
  user-management:
    sdk-key: "PKDVCLf-Hq-h-kCzMp-L7Q/YOUR_USER_MANAGEMENT_SDK_KEY"
    poll-interval-seconds: 10
  payment:
    sdk-key: "PKDVCLf-Hq-h-kCzMp-L7Q/YOUR_PAYMENT_SDK_KEY"
    poll-interval-seconds: 10

---
spring:
  config:
    activate:
      on-profile: development

configcat:
  log-level: INFO
  user-management:
    sdk-key: "PKDVCLf-Hq-h-kCzMp-L7Q/YOUR_DEV_USER_MANAGEMENT_SDK_KEY"
    poll-interval-seconds: 30
  payment:
    sdk-key: "PKDVCLf-Hq-h-kCzMp-L7Q/YOUR_DEV_PAYMENT_SDK_KEY"
    poll-interval-seconds: 30

---
spring:
  config:
    activate:
      on-profile: production

configcat:
  log-level: WARN
  user-management:
    sdk-key: "${CONFIGCAT_USER_MANAGEMENT_SDK_KEY}"
    poll-interval-seconds: 60
  payment:
    sdk-key: "${CONFIGCAT_PAYMENT_SDK_KEY}"
    poll-interval-seconds: 60