spring:
  application:
    name: configcat-demo
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

---
# Local Environment
spring:
  config:
    activate:
      on-profile: local

configcat:
  log-level: INFO
  user-management:
    sdk-key: ${CONFIGCAT_USER_MANAGEMENT_SDK_KEY_LOCAL}
    poll-interval-seconds: 30
  payment:
    sdk-key: ${CONFIGCAT_PAYMENT_SDK_KEY_LOCAL}
    poll-interval-seconds: 30

---
# Production Environment
spring:
  config:
    activate:
      on-profile: production

configcat:
  log-level: WARNING
  user-management:
    sdk-key: ${CONFIGCAT_USER_MANAGEMENT_SDK_KEY_PRODUCTION}
    poll-interval-seconds: 60
  payment:
    sdk-key: ${CONFIGCAT_PAYMENT_SDK_KEY_PRODUCTION}
    poll-interval-seconds: 60
